import Head from 'next/head';
import TableAnt from '../components/TableAnt';
import Link from 'next/link';

import { Layout } from 'antd';
import { Row, Col } from 'antd';
import { wrapper } from '../redux/store';
import { connect, useDispatch, useSelector } from 'react-redux';
import { listPredios } from '../redux/action/prediosActions';
import { bindActionCreators } from 'redux';
import React from 'react';

const { Header, Content } = Layout;

const Home = ({ predios }) => {
  // we can use hooks or connect
  // const { predios } = useSelector((state) => state);
  // console.log(predios);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Row justify='center'>
        <Col xs={23}>
          <Header></Header>
          <Content>
            <h1>Tabla for catastros</h1>
            <Link href='/predios/new/'>
              <h2>
                <a>Nuevo predio</a>
              </h2>
            </Link>
            <TableAnt data={predios} />
          </Content>
        </Col>
      </Row>
    </>
  );
};

export const getStaticProps = wrapper.getStaticProps(
  (store) =>
    async ({ preview }) => {
      console.log('2. Page.getStaticProps uses the store to dispatch things');
      await store.dispatch(listPredios());
    }
);

const mapStateToProps = (state) => {
  return {
    predios: state.prediosList,
  };
};

// const mapDispatchToProps = (dispatch) => {
//   return {
//     listPredios: bindActionCreators(listPredios, dispatch),
//   };
// };

export default connect(mapStateToProps, null)(Home);
