import Head from 'next/head';
import TableAnt from '../components/TableAnt';
import Link from 'next/link';

import { Layout } from 'antd';
import { Row, Col } from 'antd';

const { Header, Footer, Content } = Layout;

export default function Home({ data }) {
  // console.log(data);
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Row justify='center'>
        <Col xs={20}>
          <Header></Header>
          <Content>
            Header
            <h1>Catastros</h1>
            <p>Table for catastros</p>
            Content
            <h1>
              <Link href='/predios/edit'>
                <a>Edit link</a>
              </Link>
            </h1>
            <TableAnt data={data} />
          </Content>

          <Footer>Footer</Footer>
        </Col>
      </Row>
    </Layout>
  );
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/predios');
  const data = await res.json();

  return {
    props: { data }, // will be passed to the page component as props
  };
}
