import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button } from 'antd';
import TableAnt from '../components/TableAnt';

export default function Home({ data }) {
  // console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Catastros</h1>

        <p className={styles.description}>Table for catastros</p>

        <TableAnt data={data} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/predios');
  const data = await res.json();

  return {
    props: { data }, // will be passed to the page component as props
  };
}
